apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.modpacks.claimName }}
spec:
  storageClassName: {{ .Values.persistence.modpacks.storageClass }}
  accessModes:
    - {{ .Values.persistence.modpacks.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.modpacks.size }}
