apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    app: {{ include "minecraft.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: minecraft
      port: {{ .Values.service.port }}
      targetPort: 25565
  selector:
    app: {{ include "minecraft.name" . }}
